=== Addisonstumpf/arkham-cards-data/scenario.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "schema/scenario.schema.json",
  "definitions": {      
    "resolution": {
      "$id": "#resolution",
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "text": {
          "type": "string"
        },
        "resolution": {
          "type": "string"
        },
        "steps": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    }
  },
  "type": "object",
  "properties": {
    "scenarioName": {
      "type": "string"
    },
    "setup": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "resolutions": {
      "type": "array",
      "items": {
        "$ref": "#resolution"
      }
    },
    "steps": {
      "type": "array",
      "items": {
        "$ref": "schema/step.schema.json#/definitions/step"
      }
    },
    "interlude": {
      "type": "boolean"
    }
  },
  "required": [
    "scenarioName",
    "setup",
    "steps"
  ],
  "additionalProperties": false
}

=== Addisonstumpf/arkham-cards-data/campaigns/tfa/restless_nights.json
{
  "scenarioName": "Restless Nights",
  "interlude": true,
  "setup": [
    "prologue"
  ],
  "steps": [
    {
      "id": "prologue",
      "type": "story",
      "text": "Inside the chamber that contained the terrible beast, you find the missing townsfolk and the others from Arkham; they are bound and shackled. You also find several documents that suggest the creature you found isn’t the only one of its kind in Dunwich. You free the creature’s victims from their bonds, and they offer you their thanks. You begin to plan your next move."
    }
  ]
}

=== Addisonstumpf/arkham-cards-data/campaigns/ptc/lost_soul.json
{
  "scenarioName": "Lunacy's Reward",
  "interlude": true,
  "setup": [
    "daniel_choice"
  ],
  "steps": [
    {
      "id": "daniel_choice",
      "type": "input",
      "input": {
        "type": "choose_one",
        "choices": [
          {
            "text": "If the [[Ally]] version of Daniel Chesterfield was in play when the scenario ended",
            "resolution": "daniel_survived"
          },
          {
            "text": "If the [[Lunatic]] version of Daniel Chesterfield was in play when the scenario ended",
            "resolution": "daniel_possessed"
          },
          {
            "text": "If neither version of Daniel Chesterfield was in play when the scenario ended",
            "resolution": "daniel_did_not_survive"
          }
        ]
      }
    },
    {
      "id": "earn_2_xp",
      "text": "Each investigator earns 2 additional experience as they gain insight into the machinations of the Tattered King.",
       "effects": [
          {
            "type": "earn_xp",
            "investigator": "all",
            "bonus": 2    
          }
        ]
    },
    {
      "id": "earn_1_xp",
      "text": "Each investigator earns 1 additional experience as they gain insight into the machinations of the Tattered King.",
       "effects": [
          {
            "type": "earn_xp",
            "investigator": "all",
            "bonus": 1
          }
        ]
    },
    {
      "id": "warning_choice",
      "type": "input",
      "input": {
        "type": "choose_one",
        "choices": [
          {
            "text": "Possession? Oaths? There must be another explanation for all of this",
            "resolution": "ignore_the_warning"
          },
          {
            "text": "We must heed Daniel’s warning. We must not speak the name of the King in Yellow.",
            "resolution": "head_the_warning"
          },
          {
            "text": "If neither version of Daniel Chesterfield was in play when the scenario ended",
            "resolution": "daniel_did_not_survive"
          }
        ]
      }
    },
    {
      "id": "forbidden_name",
      "text": "For the remainder of the campaign, any time an investigator speaks the name of HASTUR aloud during a scenario (or during the setup of a scenario), that investigator must immediately take 1 horror."
    }
  ],
  "resolutions": [
    {
      "id": "daniel_survived",
      "title": "Daniel Survived",
      "text": "ou decide to lay low for some time in Ma’s Boarding House and hide Daniel from the authorities, although you’re unsure how long you’ll be able to stay in Arkham with an escaped asylum patient. Daniel is a loose cannon, dazed and unresponsive one moment, and screaming for his life the next. It takes several days for him to realize he’s no longer institutionalized, which for some reason makes him even more terrified. “He’s coming for me, he’s coming for me!” he rambles, sometimes for hours at a time. Finally, during an unusually warm and starry night, Daniel is calm enough to open up to you. “The King in Yellow, it’s not just a play,” he explains. “It’s a being named Hastur, and He’s already claimed me. But there’s still time for you. You are not yet possessed. You have yet to speak the Oath. Whatever you do, speak not his name. Do not give in.” You ask him about the strange events that have been happening across town, and of the cultists and creatures you’ve encountered. “They are trying to find Carcosa,” he says matter-of-factly. You recognize the name as the fictional city from the play, the one The King in Yellow rules over. “They want to release Hastur from His prison. But you!—You can open the way to Carcosa before they do! You can seal Hastur for good!” He grips you tightly as he rants. “Quickly, before the Stranger discovers our plan!”\nHours later, Daniel is incoherent and unresponsive once more. You take a long walk to ease your thoughts, mulling over this new information. You’re unsure what to make of his wild claims. Before you can make a decision about what to do next, you return to find the door to your room broken open. Daniel lies in a heap on the ground, his face colorless and body limp. Judging from the bruising around his neck, you surmise that he has been choked to death.",
      "steps": ["earn_2_xp", "warning_choice"]      
    },
    {
      "id": "daniel_did_not_survive",
      "title": "Daniel Did Not Survive",
      "text": "You decide to lay low for some time in Ma’s Boarding House, unsure whether news of the events at the asylum will get out to the general public. You take this time to make extensive notes of the events you’ve experienced thus far, including the brief dialogue between you and Daniel. He’d spoke of The King in Yellow as if it were an actual being, and even named it. “Hastur.” He’d rambled and muttered and screeched other phrases, as well. You doubt you’ll ever forget them. “He made us speak the Oath.” “The price was paid.” “They are opening the path to Carcosa.” For hours, you think about Daniel’s warning to you, which he begged you to heed: “Do not speak His name.” His final moments play out in your mind over and over again.",
      "steps": ["warning_choice"]
    },
    {
      "id": "daniel_possessed",
      "title": "Daniel Was Possessed",
      "text": "You decide to lay low for some time in Ma’s Boarding House, unsure whether news of the events at the asylum will get out to the general public. You take this time to make extensive notes of the events you’ve experienced thus far, including the brief dialogue between you and Daniel. He’d spoke of The King in Yellow as if it were an actual being, and even named it. “Hastur.” He’d rambled and muttered and screeched other phrases, as well. You doubt you’ll ever forget them. “He made us speak the Oath.” “The price was paid.” “They are opening the path to Carcosa.”\nOn the third night, you return to your room to find the door broken open. You enter cautiously, wondering if the police are onto you. Or worse, the Stranger. You are surprised to find the body of Daniel Chesterfield instead, lying on the ground with a pained, wide-eyed expression on his face. He is dead. His eyes are bloodshot and yellow, and he clutches a copy of The King in Yellow in his stiff hands. You pry the playbook from his deathly grasp and examine it. Daniel has scribbled notes in the margins of each page, mostly incomprehensible, but with a few lucid standouts. The first time the fictional city of Carcosa is mentioned, scrawled next to it Daniel has written:\n<fancy>Carcosa is real\nDo not let them open the path</fancy>\nWhen Cassilda speaks of the tattered king, Daniel has written:<fancy>Hastur is the king in tatters\nlocked in his prison in the stars\nseal him away and stop this madness!</fancy>Your mind swims with questions. How did he escape the asylum? How did he die? And why does he appear human to your eyes now? With little time to spare, you clean the room of your belongings and flee. Daniel’s words, which he begged you to heed, play out in your mind over and over again.",
      "steps": ["warning_choice"]
    },
    {
      "id": "ignore_the_warning",
      "title": "Ignore the Warning",
      "text": "For hours, you struggle with this insight into The King in Yellow. What is true? What is real? Only you can sort through this madness.",
      "steps": ["ignored_daniels_warning", "mark_2_doubt", "slay_vips", "add_cultists"]
    },
    {
      "id": "heed_the_warning",
      "title": "Heed the Warning",
      "text": "For hours, you struggle with this insight into <i>The King in Yellow</i>. What is true? What is real? Only you can sort through this madness.",
      "steps": ["heeded_daniels_warning", "mark_2_conviction", "earn_1_xp", "forbidden_name"]
    }
  ]
}

=== Addisonstumpf/arkham-cards-data/campaigns/ptc/lunacys_reward.json
{
  "scenarioName": "Lunacy's Reward",
  "interlude": true,
  "setup": [
    "house_choice"
  ],

  "steps": [
    {
      "id": "house_choice",
      "input": {
        "type": "choose_one",
        "choices": [
          {
            "text": "Things seem to have calmed down. Perhaps we should go back inside and investigate further.",
            "resolution": "reward_1"
          },
          {
            "text": "I don’t trust this place one bit. Let’s block the door and get the hell out of here!",
            "resolution": "reward_2"
          },
          {
            "text": "If these people are allowed to live, these horrors will only repeat themselves. We have to put an end to this. We have to <i>kill them.</i>",
            "resolution": "reward_3"
          }
        ]
      }
    },
    {
      "id": "why_go_back",
      "text": "Why would you go back inside?"
    },
    {
      "id": "door_wont_stop_them",
      "text": "That door isn't going to stop them."
    },
    {
      "id": "did_what_had_to_be_done",
      "text": "You did what had to be done... Right?"
    },
    {
      "id": "fled_dinner_party",
      "effects": [
        {
          "type": "campaign_log",
          "section": "campaign_log",
          "id": "fled_dinner_party",
          "text": "you fled the dinner party."
        }
      ]
    },
    {
      "id": "intruded_on_secret_meeting",
      "text": "Mark one <b>Doubt</b> in your Campaign Log.",
      "effects": [
        {
          "type": "campaign_log",
          "section": "campaign_log",
          "id": "intruded_on_secret_meeting",
          "text": "you intruded on a secret meeting."
        },
        {
          "type": "campaign_log",
          "section": "doubt",
          "count": 1
        }
      ]
    },
    {
      "id": "slayed_the_monsters",
      "text": "Mark one <b>Conviction</b> in your Campaign Log.",
      "effects": [
        {
          "type": "campaign_log",
          "section": "campaign_log",
          "id": "slayed_the_monsters",
          "text": "you slayed the monsters at the dinner party."
        },
        {
          "type": "campaign_log",
          "section": "conviction",
          "count": 1
        }
      ]
    },
    {
      "id": "add_elder_things",
      "text": "Remove all [cultist], [tablet], and [elder_thing] tokens from the chaos bag. Then, add 2 [elder_thing] tokens to the chaos bag.",
      "effects": [
        {
          "type": "remove_chaos_token",
          "values": [
            "cultist", 
            "cultist",
            "tablet",
            "tablet",
            "elder_thing",
            "elder_thing"
          ]
        },
        {
          "type": "add_chaos_token",
          "values": [
            "elder_thing",
            "elder_thing"
          ]
        }
      ]
    },
    {
      "id": "add_tablets",
      "text": "Remove all [cultist], [tablet], and [elder_thing] tokens from the chaos bag. Then, add 2 [tablet] tokens to the chaos bag.",
      "effects": [
        {
          "type": "remove_chaos_token",
          "values": [
            "cultist", 
            "cultist",
            "tablet",
            "tablet",
            "elder_thing",
            "elder_thing"
          ]
        },
        {
          "type": "add_chaos_token",
          "values": [
            "tablet",
            "tablet"
          ]
        }
      ]
    },
    {
      "id": "add_cultists",
      "text": "Remove all [cultist], [tablet], and [elder_thing] tokens from the chaos bag. Then, add 2 [cultist] tokens to the chaos bag.",
      "effects": [
        {
          "type": "remove_chaos_token",
          "values": [
            "cultist", 
            "cultist",
            "tablet",
            "tablet",
            "elder_thing",
            "elder_thing"
          ]
        },
        {
          "type": "add_chaos_token",
          "values": [
            "cultist",
            "cultist"
          ]
        }
      ]
    },
    {
      "id": "slay_vips",
      "effects": [
        {
          "type": "campaign_log",
          "section": "vips_slain",
          "card": "03065b"
        },
        {
          "type": "campaign_log",
          "section": "vips_slain",
          "card": "03066b"
        },
        {
          "type": "campaign_log",
          "section": "vips_slain",
          "card": "03067b"
        },
        {
          "type": "campaign_log",
          "section": "vips_slain",
          "card": "03068b"
        },
        {
          "type": "campaign_log",
          "section": "vips_slain",
          "card": "03069b"
        }
      ]
    }
  ],
  "resolutions": [
    {
      "id": "reward_1",
      "title": "Lunacy's Reward 1",
      "text": "The change in the atmosphere has you curious. What if it was all a trick of your mind? What if the hauntings that follow The King in Yellow are but transitory? The answers to all of your questions might lie inside. Cautiously, you open the front door to the manor once again. Reassuring jazz and the clamor of casual conversation grow louder as you step inside. The enticing smell of roasted pork wafts through the air. As you suspected, the signs of struggle and oddities you noticed before have vanished without explanation. Then, as you turn the corner into the dining room, you find the Stranger speaking with another man—tall, mustached, wearing a fine black suit, and holding a silver-handled cane. The Stranger turns to you, his gaze drills through your mind, and your vision swims with agony. Before you realize it, you are running as fast as you can, toppling through the front doorway in a haze of pain and disorientation. Without time to catch your breath, you race to your vehicle and speed away, hands trembling upon the steering wheel.",
      "steps": ["why_go_back", "intruded_on_secret_meeting", "add_elder_things"]      
    },
    {
      "id": "reward_2",
      "title": "Lunacy's Reward 2",
      "text": "You can’t trust your senses. This is all a trick, an attempt to lure you back inside. You’re no safer now than you were before. Swallowing your fear, you set to work barricading the front door of the manor using several of the heavy stone benches lining the cobblestone path in the front yard. You hope it’s enough, but you aren’t willing to stick around to find out. As soon as you’re done, you head back to your vehicle and drive toward Southside, where you hope to find answers.",
      "steps": ["door_wont_stop_them", "fled_dinner_party", "add_tablets"]
    },
    {
      "id": "reward_3",
      "title": "Lunacy's Reward 3",
      "text": "You dare not risk stepping back inside that madhouse. But you can’t let the monstrosities run amok, either. You root through the open garage for a few supplies, finding an old hose, an empty gasoline canister, and some matches. Knowing what you must do, you first siphon some gas from Mrs. Dumaine’s Oakland 6-54A. You spread the gasoline across the front porch, inside the garage, and around the manor’s outer walls. From there, all it takes is several matches to start the blaze. You watch from the front yard as the manor is eventually consumed by the flames. The sounds of crackling fire and snapping wood and the screeching of dying horrors fills the street. Satisfied, you head back to your vehicle and tear off toward Southside, full of grim determination.",
      "steps": ["did_what_had_to_be_done", "slayed_the_monsters", "slay_vips", "add_cultists"]
    }
  ]
}

=== Addisonstumpf/arkham-cards-data/campaigns/tfa/prologue.json
{
  "scenarioName": "Prologue",
  "interlude": true,
  "setup": [
    "intro",
    "expedition_leader"
  ],
  "steps": [
    {
      "id": "intro",
      "type": "story",
      "text": "<fancy>Tuesday, June 2nd, 1925</fancy>\nThere will be no rest for us this summer, it seems.\nToday I met with Harlan Earnstone, a historical theorist at Miskatonic University and an old friend of mine. He’d said he had a job offer for me, but frankly, I didn’t know what to expect.\nHarlan introduced me to an associate of his: Alejandro Vela, a distinguished historian from across the southern border. Mr. Vela is a graduate of a prestigious university in Mexico City, and has spent many years researching the Aztec Empire. He claims that he has found evidence regarding the existence of an unheard-of Aztec city-state called Eztli. His strange and unprecedented findings were not accepted by the university, and he’s become a pariah among his peers.\nAlejandro came to Arkham to seek funding for an expedition into the rainforests of southern Mexico, where he believes that the ruins of the Eztli altepetl lie undiscovered. His description of this city-state’s origins defies modern understanding of Mesoamerican history. Despite this— or, knowing my old friend, because of this—Harlan is enthralled by Alejandro’s discoveries. Miskatonic University has agreed to fund the expedition (albeit meagerly), and Harlan wants me to go along.\nThe way I see it, there’s a good chance we’re looking for something that doesn’t even exist. But if there’s even a slight chance these Eztli people existed, the historical significance would be profound. We debated the issue for some time, but in the end, we accepted Alejandro’s offer. Preparations are underway, and we should be setting off by the end of the month. With any luck, we’ll have this journal filled with all manner of interesting discoveries. If not, perhaps it’ll be a nice wedge to place beneath Harlan’s lopsided desk."
    },
    {
      "id": "expedition_leader",
      "text": "If Ursula Downs, Leo Anderson, or Monterey Jack was chosen as an investigator for this campaign: Choose one of those investigators to be the expedition leader. That investigator begins Scenarios I and II as the lead investigator."
    },
    {
      "id": "supplies",
      "text": "As an outcast from academia, funding for Alejandro’s expedition is limited. Each investigator must choose supplies to bring for the expedition. In the Campaign Log, under each investigator’s “Supplies” section, record the supplies that investigator chose to bring. <i>(Note: Provisions and Medicine can be taken more than once by recording their name multiple times and spending the appropriate number of supply points each time.)</i>"
    }
  ]
}
